title: Insight in Science and Medicine
description: >-
  A peer-reviewed journal of translational research and clinical science
  emphasizing reliability and data reusability. This journal is published
  under CC BY 4.0. ISSN: 3069-8898
author: Genomics.X
email: 228049428+jianlizhaodr@users.noreply.github.com
baseurl: "/insight-in-science-and-medicine"
url: "https://jianlizhaodr.github.io"
github_username: jianlizhaodr

theme: minima
markdown: kramdown
highlighter: rouge
permalink: /:collection/:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-scholar

collections:
  biotech:
    output: true
    permalink: /biotech/:path/

defaults:
  - scope:
      path: ""
      type: biotech
    values:
      layout: post
      topic: biotech

scholar:
  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: bib
  style: apa
  sort_by: year
  order: descending

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
  - .github
